# -*- coding: utf-8 -*-
"""Mango_Inception_v1_Mango_Inception_v1_image size 224.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AcXyiNKx3FbEQInzJjXgwKUajOERjSLJ
"""

import os
import zipfile
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import Model
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import img_to_array, load_img

import zipfile
from google.colab import drive
drive.mount('/content/gdrive')

local_zip = '/content/gdrive/MyDrive/Capstone/Mango.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall()

zip_ref.close()

def train_val_generators(TRAINING_DIR, VALIDATION_DIR):
  train_datagen = ImageDataGenerator(rescale=1.0/255.,
                                     rotation_range=180,
                                     width_shift_range=0.2,
                                     height_shift_range=0.2,
                                     shear_range=0.2,
                                     zoom_range=0.2,
                                     horizontal_flip=True,
                                     fill_mode='nearest')

  train_generator = train_datagen.flow_from_directory(directory=TRAINING_DIR,
                                                      batch_size=64,
                                                      class_mode='categorical',
                                                      target_size=(224, 224))

  validation_datagen = ImageDataGenerator( rescale = 1.0/255.)
  validation_generator = validation_datagen.flow_from_directory(directory=VALIDATION_DIR,
                                                                batch_size=32,
                                                                class_mode='categorical',
                                                                target_size=(224, 224))
  return train_generator, validation_generator

train_dir = '/content/Mango/train'
val_dir = '/content/Mango/test'
train_generator, validation_generator = train_val_generators(train_dir, val_dir)

from tensorflow.keras.applications.inception_v3 import InceptionV3
def create_pre_trained_model():
  pre_trained_model = InceptionV3(input_shape = (224, 224, 3),
                                  include_top = False,
                                  weights = 'imagenet')

  # Make all the layers in the pre-trained model non-trainable
  for layers in pre_trained_model.layers:
    layers.trainable = False

  return pre_trained_model

pre_trained_model = create_pre_trained_model()

# Print the model summary
pre_trained_model.summary()

def create_final_model(pre_trained_model, last_output):
  x = layers.Flatten()(last_output)

  x = layers.Dense(32, activation='relu')(x)
  x = tf.keras.layers.BatchNormalization()(x)
  x = layers.Dropout(0.4)(x)
  x = layers.Dense(8, activation='softmax')(x)

  # Create the complete model by using the Model class
  model = Model(inputs=pre_trained_model.input, outputs=x)
  model.compile(optimizer = RMSprop(learning_rate=0.01),
                loss = 'categorical_crossentropy',
                metrics = ['accuracy'])

  return model

acc_ckp_path = '/content/gdrive/MyDrive/Capstone/mango_inception_v1_changeSize.h5'
acc_checkpoint = tf.keras.callbacks.ModelCheckpoint(acc_ckp_path, monitor='accuracy', verbose=2,
    save_best_only=True, mode='auto', save_freq='epoch')

val_acc_ckp_path = '/content/gdrive/MyDrive/Capstone/mango_inception_v1_changeSize.h5'
val_acc_checkpoint = tf.keras.callbacks.ModelCheckpoint(val_acc_ckp_path, monitor='val_accuracy', verbose=2,
    save_best_only=True, mode='auto', save_freq='epoch')

class stopEpoch(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy') >= 0.98 and logs.get('val_accuracy') > 0.90):
      print("\nThreshold achieve!\n")
      self.model.stop_training = True

last_layer = pre_trained_model.get_layer('mixed7')
print('last layer output shape: ', last_layer.output_shape)
last_output = last_layer.output

model = create_final_model(pre_trained_model, last_output)
history = model.fit(train_generator,
                    validation_data = validation_generator,
                    epochs = 100,
                    verbose = 2,
                    callbacks=[acc_checkpoint, val_acc_checkpoint, stopEpoch()])

# from PIL import Image
# import numpy as np
# import cv2

# image = np.array(Image.open("/content/mango_sakit.jpg").resize((224, 224)).convert("RGB"))/255.0
# image = np.expand_dims(image, axis=0)
# predict = model.predict(image)
# print(predict)
# max_index = np.argmax(predict)

# if(max_index == 0):
#   print("This is a first")
# elif (max_index == 1):
#   print("This is a second")
# elif (max_index == 2):
#   print("This is a third")
# elif (max_index == 3):
#   print("This is a fourth")
# elif (max_index == 4):
#   print("This is a fifth")
# elif (max_index == 5):
#   print("This is a sixth")
# elif (max_index == 6):
#   print("This is a seventh")
# elif (max_index == 7):
#   print("This is a eighth")
# else:
#   print("This is not included")

from PIL import Image
import numpy as np
model = tf.keras.models.load_model('/content/gdrive/MyDrive/Capstone/mango_inception_v1_changeSize.h5')

def predict_disease(test_dir):
  list_test_image = os.listdir(test_dir)
  value=[]

  for list in list_test_image:
    image = os.path.join(test_dir, list)
    image = np.array(Image.open(image).resize((224, 224)).convert("RGB"))/255.0
    image = np.expand_dims(image, axis=0)
    predict = model.predict(image)
    print(predict)
    max_index = np.argmax(predict)
    if(max_index == 0):
        pred = "Anthracnose"
    elif(max_index == 1):
      pred = "Bacterial Canker"
    elif(max_index == 2):
      pred = "Cutting Weevil"
    elif(max_index == 3):
      pred = "Die Back"
    elif(max_index == 4):
      pred = "Gall Midge"
    elif(max_index == 5):
      pred = "Healthy"
    elif(max_index == 6):
      pred = "Powdery Mildew"
    elif(max_index == 7):
      pred = "Sooty Mould"

    true_pred = test_dir.split("/")[-1]

    if(pred == true_pred):
      value.append(1)
    else:
      value.append(0)
  result = print(f'Accuracy of predict {true_pred} was ' + str(np.mean(value)))
  return result

predict_disease('/content/implement/Anthracnose')

predict_disease('/content/implement/Die Back')

predict_disease('/content/implement/Gall Midge')

predict_disease('/content/implement/Healthy')

predict_disease('/content/implement/Powdery Mildew')